[veliciny.l]
unit = "cm"
hodnoty = [28.6, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]   # kovová

[veliciny.E]
unit = "Lux"
hodnoty = [13, 12, 11, 11, 11, 9, 9, 9, 8, 8, 8]   # zelená koule

[veliciny.I]
unit = "μA"
hodnoty = [2.16, 1.95, 1.75, 1.65, 1.47, 1.25, 1.18, 10.6, 10.01, 1]   # červená koule